# Generated by Django 2.2.5 on 2021-08-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210802_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
    ]
